<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Region;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $region = Region::all();
        if($region->isEmpty()){
            //Regiones
            DB::table('regions')->insert(['name' => "Región de Arica y Parinacota", 'abbreviation' => "XV", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Tarapacá", 'abbreviation' => "I", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Antofagasta", 'abbreviation' => "II", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Atacama", 'abbreviation' => "III", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Coquimbo", 'abbreviation' => "IV", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Valparaíso", 'abbreviation' => "V", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región Metropolitana de Santiago", 'abbreviation' => "RM", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región del Libertador General Bernardo O'Higgins", 'abbreviation' => "VI", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región del Maule", 'abbreviation' => "VII", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Ñuble", 'abbreviation' => "XVI", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región del Biobío", 'abbreviation' => "VIII", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de La Araucanía", 'abbreviation' => "IX", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Los Ríos", 'abbreviation' => "XIV", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Los Lagos", 'abbreviation' => "X", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Aysén del General Carlos Ibáñez del Campo", 'abbreviation' => "XI", 'created_at' => now(), 'updated_at' => now()]);
            DB::table('regions')->insert(['name' => "Región de Magallanes y de la Antártica Chilena", 'abbreviation' => "XII", 'created_at' => now(), 'updated_at' => now()]);

            //ciudades
            DB::table('cities')->insert(['name' => "Arica", 'abbreviation' => "Arica", 'region_id' =>  1, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Putre", 'abbreviation' => "Putre", 'region_id' =>  1, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Iquique", 'abbreviation' => "Iquique", 'region_id' =>  2, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Pozo Almonte", 'abbreviation' => "Pozo Almonte", 'region_id' =>  2, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Antofagasta", 'abbreviation' => "Antofagasta", 'region_id' =>  3, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Calama", 'abbreviation' => "Calama", 'region_id' =>  3, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Tocopilla", 'abbreviation' => "Tocopilla", 'region_id' =>  3, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Chañaral", 'abbreviation' => "Chañaral", 'region_id' =>  4, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Copiapó", 'abbreviation' => "Copiapó", 'region_id' =>  4, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Vallenar", 'abbreviation' => "Vallenar", 'region_id' =>  4, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Illapel", 'abbreviation' => "Illapel", 'region_id' =>  5, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Coquimbo", 'abbreviation' => "Coquimbo", 'region_id' =>  5, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Ovalle", 'abbreviation' => "Ovalle", 'region_id' =>  5, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Hanga Roa", 'abbreviation' => "Hanga Roa", 'region_id' =>  6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Los Andes", 'abbreviation' => "Los Andes", 'region_id' =>  6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Quilpué", 'abbreviation' => "Quilpué", 'region_id' =>  6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "La Ligua", 'abbreviation' => "La Ligua", 'region_id' =>  6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Quillota", 'abbreviation' => "Quillota", 'region_id' =>  6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "San Antonio", 'abbreviation' => "San Antonio", 'region_id' =>  6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "San Felipe", 'abbreviation' => "San Felipe", 'region_id' =>  6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Valparaíso", 'abbreviation' => "Valparaíso", 'region_id' =>  6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Colina", 'abbreviation' => "Colina", 'region_id' =>  7, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Puente Alto", 'abbreviation' => "Puente Alto", 'region_id' =>  7, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "San Bernardo", 'abbreviation' => "San Bernardo", 'region_id' =>  7, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Melipilla", 'abbreviation' => "Melipilla", 'region_id' =>  7, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Santiago", 'abbreviation' => "Santiago", 'region_id' =>  7, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Talagante", 'abbreviation' => "Talagante", 'region_id' =>  7, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Rancagua", 'abbreviation' => "Rancagua", 'region_id' =>  8, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Pichilemu", 'abbreviation' => "Pichilemu", 'region_id' =>  8, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "San Fernando", 'abbreviation' => "San Fernando", 'region_id' =>  8, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Cauquenes", 'abbreviation' => "Cauquenes", 'region_id' =>  9, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Curicó", 'abbreviation' => "Curicó", 'region_id' =>  9, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Linares", 'abbreviation' => "Linares", 'region_id' =>  9, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Talca", 'abbreviation' => "Talca", 'region_id' =>  9, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Bulnes", 'abbreviation' => "Bulnes", 'region_id' =>  10, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Quirihue", 'abbreviation' => "Quirihue", 'region_id' =>  10, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "San Carlos", 'abbreviation' => "San Carlos", 'region_id' =>  10, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Lebu", 'abbreviation' => "Lebu", 'region_id' =>  11, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Los Ángeles", 'abbreviation' => "Los Ángeles", 'region_id' =>  11, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Concepción", 'abbreviation' => "Concepción", 'region_id' =>  11, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Temuco", 'abbreviation' => "Temuco", 'region_id' =>  12, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Angol", 'abbreviation' => "Angol", 'region_id' =>  12, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "La Unión", 'abbreviation' => "La Unión", 'region_id' =>  13, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Valdivia", 'abbreviation' => "Valdivia", 'region_id' =>  13, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Castro", 'abbreviation' => "Castro", 'region_id' =>  14, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Puerto Montt", 'abbreviation' => "Puerto Montt", 'region_id' =>  14, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Osorno", 'abbreviation' => "Osorno", 'region_id' =>  14, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Chaitén", 'abbreviation' => "Chaitén", 'region_id' =>  14, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Puerto Aysén", 'abbreviation' => "Puerto Aysén", 'region_id' =>  15, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Cochrane", 'abbreviation' => "Cochrane", 'region_id' =>  15, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Coyhaique", 'abbreviation' => "Coyhaique", 'region_id' =>  15, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Chile Chico", 'abbreviation' => "Chile Chico", 'region_id' =>  15, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Puerto Williams", 'abbreviation' => "Puerto Williams", 'region_id' =>  16, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Punta Arenas", 'abbreviation' => "Punta Arenas", 'region_id' =>  16, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Porvenir", 'abbreviation' => "Porvenir", 'region_id' =>  16, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('cities')->insert(['name' => "Puerto Natales", 'abbreviation' => "Puerto Natales", 'region_id' =>  16, 'created_at' => now(), 'updated_at' => now()]);

            //comunas
            DB::table('communes')->insert(['name' => "Arica", 'abbreviation' => "Arica", 'city_id' =>1, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Camarones", 'abbreviation' => "Camarones", 'city_id' =>1, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "General Lagos", 'abbreviation' => "General Lagos", 'city_id' =>2, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Putre", 'abbreviation' => "Putre", 'city_id' =>2, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Alto Hospicio", 'abbreviation' => "Alto Hospicio", 'city_id' =>3, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Iquique", 'abbreviation' => "Iquique", 'city_id' =>3, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Camiña", 'abbreviation' => "Camiña", 'city_id' =>4, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Colchane", 'abbreviation' => "Colchane", 'city_id' =>4, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Huara", 'abbreviation' => "Huara", 'city_id' =>4, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pica", 'abbreviation' => "Pica", 'city_id' =>4, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pozo Almonte", 'abbreviation' => "Pozo Almonte", 'city_id' =>4, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Antofagasta", 'abbreviation' => "Antofagasta", 'city_id' =>5, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Mejillones", 'abbreviation' => "Mejillones", 'city_id' =>5, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Sierra Gorda", 'abbreviation' => "Sierra Gorda", 'city_id' =>5, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Taltal", 'abbreviation' => "Taltal", 'city_id' =>5, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Calama", 'abbreviation' => "Calama", 'city_id' =>6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Ollagüe", 'abbreviation' => "Ollagüe", 'city_id' =>6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Pedro de Atacama", 'abbreviation' => "San Pedro de At", 'city_id' =>6, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "María Elena", 'abbreviation' => "María Elena", 'city_id' =>7, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Tocopilla", 'abbreviation' => "Tocopilla", 'city_id' =>7, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chañaral", 'abbreviation' => "Chañaral", 'city_id' =>8, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Diego de Almagro", 'abbreviation' => "Diego de Almagr", 'city_id' =>8, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Caldera", 'abbreviation' => "Caldera", 'city_id' =>9, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Copiapó", 'abbreviation' => "Copiapó", 'city_id' =>9, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Tierra Amarilla", 'abbreviation' => "Tierra Amarilla", 'city_id' =>9, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Alto del Carmen", 'abbreviation' => "Alto del Carmen", 'city_id' =>10, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Freirina", 'abbreviation' => "Freirina", 'city_id' =>10, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Huasco", 'abbreviation' => "Huasco", 'city_id' =>10, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Vallenar", 'abbreviation' => "Vallenar", 'city_id' =>10, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Canela", 'abbreviation' => "Canela", 'city_id' =>11, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Illapel", 'abbreviation' => "Illapel", 'city_id' =>11, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Los Vilos", 'abbreviation' => "Los Vilos", 'city_id' =>11, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Salamanca", 'abbreviation' => "Salamanca", 'city_id' =>11, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Andacollo", 'abbreviation' => "Andacollo", 'city_id' =>12, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Coquimbo", 'abbreviation' => "Coquimbo", 'city_id' =>12, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Higuera", 'abbreviation' => "La Higuera", 'city_id' =>12, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Serena", 'abbreviation' => "La Serena", 'city_id' =>12, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Paihuano", 'abbreviation' => "Paihuano", 'city_id' =>12, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Vicuña", 'abbreviation' => "Vicuña", 'city_id' =>12, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Combarbalá", 'abbreviation' => "Combarbalá", 'city_id' =>13, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Monte Patria", 'abbreviation' => "Monte Patria", 'city_id' =>13, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Ovalle", 'abbreviation' => "Ovalle", 'city_id' =>13, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Punitaqui", 'abbreviation' => "Punitaqui", 'city_id' =>13, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Río Hurtado", 'abbreviation' => "Río Hurtado", 'city_id' =>13, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Isla de Pascua", 'abbreviation' => "Isla de Pascua", 'city_id' =>14, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Calle Larga", 'abbreviation' => "Calle Larga", 'city_id' =>15, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Los Andes", 'abbreviation' => "Los Andes", 'city_id' =>15, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Rinconada de Los Andes", 'abbreviation' => "Rinconada de Lo", 'city_id' =>15, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Esteban", 'abbreviation' => "San Esteban", 'city_id' =>15, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Limache", 'abbreviation' => "Limache", 'city_id' =>16, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Olmué", 'abbreviation' => "Olmué", 'city_id' =>16, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quilpué", 'abbreviation' => "Quilpué", 'city_id' =>16, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Villa Alemana", 'abbreviation' => "Villa Alemana", 'city_id' =>16, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cabildo", 'abbreviation' => "Cabildo", 'city_id' =>17, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Ligua", 'abbreviation' => "La Ligua", 'city_id' =>17, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Papudo", 'abbreviation' => "Papudo", 'city_id' =>17, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Petorca", 'abbreviation' => "Petorca", 'city_id' =>17, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Zapallar", 'abbreviation' => "Zapallar", 'city_id' =>17, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Hijuelas", 'abbreviation' => "Hijuelas", 'city_id' =>18, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Calera", 'abbreviation' => "La Calera", 'city_id' =>18, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Cruz", 'abbreviation' => "La Cruz", 'city_id' =>18, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Nogales", 'abbreviation' => "Nogales", 'city_id' =>18, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quillota", 'abbreviation' => "Quillota", 'city_id' =>18, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Algarrobo", 'abbreviation' => "Algarrobo", 'city_id' =>19, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cartagena", 'abbreviation' => "Cartagena", 'city_id' =>19, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "El Quisco", 'abbreviation' => "El Quisco", 'city_id' =>19, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "El Tabo", 'abbreviation' => "El Tabo", 'city_id' =>19, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Antonio", 'abbreviation' => "San Antonio", 'city_id' =>19, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Santo Domingo", 'abbreviation' => "Santo Domingo", 'city_id' =>19, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Catemu", 'abbreviation' => "Catemu", 'city_id' =>20, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Llaillay", 'abbreviation' => "Llaillay", 'city_id' =>20, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Panquehue", 'abbreviation' => "Panquehue", 'city_id' =>20, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Putaendo", 'abbreviation' => "Putaendo", 'city_id' =>20, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Felipe", 'abbreviation' => "San Felipe", 'city_id' =>20, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Santa María", 'abbreviation' => "Santa María", 'city_id' =>20, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Casablanca", 'abbreviation' => "Casablanca", 'city_id' =>21, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Concón", 'abbreviation' => "Concón", 'city_id' =>21, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Juan Fernández", 'abbreviation' => "Juan Fernández", 'city_id' =>21, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Puchuncaví", 'abbreviation' => "Puchuncaví", 'city_id' =>21, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quintero", 'abbreviation' => "Quintero", 'city_id' =>21, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Valparaíso", 'abbreviation' => "Valparaíso", 'city_id' =>21, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Viña del Mar", 'abbreviation' => "Viña del Mar", 'city_id' =>21, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Codegua", 'abbreviation' => "Codegua", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Coínco", 'abbreviation' => "Coínco", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Coltauco", 'abbreviation' => "Coltauco", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Doñihue", 'abbreviation' => "Doñihue", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Graneros", 'abbreviation' => "Graneros", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Las Cabras", 'abbreviation' => "Las Cabras", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Machalí", 'abbreviation' => "Machalí", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Malloa", 'abbreviation' => "Malloa", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Olivar", 'abbreviation' => "Olivar", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Peumo", 'abbreviation' => "Peumo", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pichidegua", 'abbreviation' => "Pichidegua", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quinta de Tilcoco", 'abbreviation' => "Quinta de Tilco", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Rancagua", 'abbreviation' => "Rancagua", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Requínoa", 'abbreviation' => "Requínoa", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Rengo", 'abbreviation' => "Rengo", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Francisco de Mostazal", 'abbreviation' => "San Francisco d", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Vicente de Tagua Tagua", 'abbreviation' => "San Vicente de ", 'city_id' =>28, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Estrella", 'abbreviation' => "La Estrella", 'city_id' =>29, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Litueche", 'abbreviation' => "Litueche", 'city_id' =>29, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Marchigüe", 'abbreviation' => "Marchigüe", 'city_id' =>29, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Navidad", 'abbreviation' => "Navidad", 'city_id' =>29, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Paredones", 'abbreviation' => "Paredones", 'city_id' =>29, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pichilemu", 'abbreviation' => "Pichilemu", 'city_id' =>29, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chépica", 'abbreviation' => "Chépica", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chimbarongo", 'abbreviation' => "Chimbarongo", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lolol", 'abbreviation' => "Lolol", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Nancagua", 'abbreviation' => "Nancagua", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Palmilla", 'abbreviation' => "Palmilla", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Peralillo", 'abbreviation' => "Peralillo", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Placilla", 'abbreviation' => "Placilla", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pumanque", 'abbreviation' => "Pumanque", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Fernando", 'abbreviation' => "San Fernando", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Santa Cruz", 'abbreviation' => "Santa Cruz", 'city_id' =>30, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cauquenes", 'abbreviation' => "Cauquenes", 'city_id' =>31, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chanco", 'abbreviation' => "Chanco", 'city_id' =>31, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pelluhue", 'abbreviation' => "Pelluhue", 'city_id' =>31, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Curicó", 'abbreviation' => "Curicó", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Hualañé", 'abbreviation' => "Hualañé", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Licantén", 'abbreviation' => "Licantén", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Molina", 'abbreviation' => "Molina", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Rauco", 'abbreviation' => "Rauco", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Romeral", 'abbreviation' => "Romeral", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Sagrada Familia", 'abbreviation' => "Sagrada Familia", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Teno", 'abbreviation' => "Teno", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Vichuquén", 'abbreviation' => "Vichuquén", 'city_id' =>32, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Colbún", 'abbreviation' => "Colbún", 'city_id' =>33, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Linares", 'abbreviation' => "Linares", 'city_id' =>33, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Longaví", 'abbreviation' => "Longaví", 'city_id' =>33, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Parral", 'abbreviation' => "Parral", 'city_id' =>33, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Retiro", 'abbreviation' => "Retiro", 'city_id' =>33, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Javier de Loncomilla", 'abbreviation' => "San Javier de L", 'city_id' =>33, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Villa Alegre", 'abbreviation' => "Villa Alegre", 'city_id' =>33, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Yerbas Buenas", 'abbreviation' => "Yerbas Buenas", 'city_id' =>33, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Constitución", 'abbreviation' => "Constitución", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Curepto", 'abbreviation' => "Curepto", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Empedrado", 'abbreviation' => "Empedrado", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Maule", 'abbreviation' => "Maule", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pelarco", 'abbreviation' => "Pelarco", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pencahue", 'abbreviation' => "Pencahue", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Río Claro", 'abbreviation' => "Río Claro", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Clemente", 'abbreviation' => "San Clemente", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Rafael", 'abbreviation' => "San Rafael", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Talca", 'abbreviation' => "Talca", 'city_id' =>34, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Bulnes", 'abbreviation' => "Bulnes", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chillán", 'abbreviation' => "Chillán", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chillán Viejo", 'abbreviation' => "Chillán Viejo", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "El Carmen", 'abbreviation' => "El Carmen", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pemuco", 'abbreviation' => "Pemuco", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pinto", 'abbreviation' => "Pinto", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quillón", 'abbreviation' => "Quillón", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Ignacio", 'abbreviation' => "San Ignacio", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Yungay", 'abbreviation' => "Yungay", 'city_id' =>35, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cobquecura", 'abbreviation' => "Cobquecura", 'city_id' =>36, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Coelemu", 'abbreviation' => "Coelemu", 'city_id' =>36, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Ninhue", 'abbreviation' => "Ninhue", 'city_id' =>36, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Portezuelo", 'abbreviation' => "Portezuelo", 'city_id' =>36, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quirihue", 'abbreviation' => "Quirihue", 'city_id' =>36, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Ránquil", 'abbreviation' => "Ránquil", 'city_id' =>36, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Treguaco", 'abbreviation' => "Treguaco", 'city_id' =>36, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Coihueco", 'abbreviation' => "Coihueco", 'city_id' =>37, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Ñiquén", 'abbreviation' => "Ñiquén", 'city_id' =>37, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Carlos", 'abbreviation' => "San Carlos", 'city_id' =>37, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Fabián", 'abbreviation' => "San Fabián", 'city_id' =>37, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Nicolás", 'abbreviation' => "San Nicolás", 'city_id' =>37, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Arauco", 'abbreviation' => "Arauco", 'city_id' =>38, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cañete", 'abbreviation' => "Cañete", 'city_id' =>38, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Contulmo", 'abbreviation' => "Contulmo", 'city_id' =>38, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Curanilahue", 'abbreviation' => "Curanilahue", 'city_id' =>38, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lebu", 'abbreviation' => "Lebu", 'city_id' =>38, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Los Álamos", 'abbreviation' => "Los Álamos", 'city_id' =>38, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Tirúa", 'abbreviation' => "Tirúa", 'city_id' =>38, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Alto Biobío", 'abbreviation' => "Alto Biobío", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Antuco", 'abbreviation' => "Antuco", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cabrero", 'abbreviation' => "Cabrero", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Laja", 'abbreviation' => "Laja", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Los Ángeles", 'abbreviation' => "Los Ángeles", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Mulchén", 'abbreviation' => "Mulchén", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Nacimiento", 'abbreviation' => "Nacimiento", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Negrete", 'abbreviation' => "Negrete", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quilaco", 'abbreviation' => "Quilaco", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quilleco", 'abbreviation' => "Quilleco", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Rosendo", 'abbreviation' => "San Rosendo", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Santa Bárbara", 'abbreviation' => "Santa Bárbara", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Tucapel", 'abbreviation' => "Tucapel", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Yumbel", 'abbreviation' => "Yumbel", 'city_id' =>39, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chiguayante", 'abbreviation' => "Chiguayante", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Concepción", 'abbreviation' => "Concepción", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Coronel", 'abbreviation' => "Coronel", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Florida", 'abbreviation' => "Florida", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Hualpén", 'abbreviation' => "Hualpén", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Hualqui", 'abbreviation' => "Hualqui", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lota", 'abbreviation' => "Lota", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Penco", 'abbreviation' => "Penco", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Pedro de la Paz", 'abbreviation' => "San Pedro de la", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Santa Juana", 'abbreviation' => "Santa Juana", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Talcahuano", 'abbreviation' => "Talcahuano", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Tomé", 'abbreviation' => "Tomé", 'city_id' =>40, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Carahue", 'abbreviation' => "Carahue", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cholchol", 'abbreviation' => "Cholchol", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cunco", 'abbreviation' => "Cunco", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Curarrehue", 'abbreviation' => "Curarrehue", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Freire", 'abbreviation' => "Freire", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Galvarino", 'abbreviation' => "Galvarino", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Gorbea", 'abbreviation' => "Gorbea", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lautaro", 'abbreviation' => "Lautaro", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Loncoche", 'abbreviation' => "Loncoche", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Melipeuco", 'abbreviation' => "Melipeuco", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Nueva Imperial", 'abbreviation' => "Nueva Imperial", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Padre Las Casas", 'abbreviation' => "Padre Las Casas", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Perquenco", 'abbreviation' => "Perquenco", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pitrufquén", 'abbreviation' => "Pitrufquén", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pucón", 'abbreviation' => "Pucón", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Saavedra", 'abbreviation' => "Saavedra", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Temuco", 'abbreviation' => "Temuco", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Teodoro Schmidt", 'abbreviation' => "Teodoro Schmidt", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Toltén", 'abbreviation' => "Toltén", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Vilcún", 'abbreviation' => "Vilcún", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Villarrica", 'abbreviation' => "Villarrica", 'city_id' =>41, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Angol", 'abbreviation' => "Angol", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Collipulli", 'abbreviation' => "Collipulli", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Curacautín", 'abbreviation' => "Curacautín", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Ercilla", 'abbreviation' => "Ercilla", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lonquimay", 'abbreviation' => "Lonquimay", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Los Sauces", 'abbreviation' => "Los Sauces", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lumaco", 'abbreviation' => "Lumaco", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Purén", 'abbreviation' => "Purén", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Renaico", 'abbreviation' => "Renaico", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Traiguén", 'abbreviation' => "Traiguén", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Victoria", 'abbreviation' => "Victoria", 'city_id' =>42, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Futrono", 'abbreviation' => "Futrono", 'city_id' =>43, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Unión", 'abbreviation' => "La Unión", 'city_id' =>43, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lago Ranco", 'abbreviation' => "Lago Ranco", 'city_id' =>43, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Río Bueno", 'abbreviation' => "Río Bueno", 'city_id' =>43, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Corral", 'abbreviation' => "Corral", 'city_id' =>44, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lanco", 'abbreviation' => "Lanco", 'city_id' =>44, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Los Lagos", 'abbreviation' => "Los Lagos", 'city_id' =>44, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Máfil", 'abbreviation' => "Máfil", 'city_id' =>44, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Mariquina", 'abbreviation' => "Mariquina", 'city_id' =>44, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Paillaco", 'abbreviation' => "Paillaco", 'city_id' =>44, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Panguipulli", 'abbreviation' => "Panguipulli", 'city_id' =>44, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Valdivia", 'abbreviation' => "Valdivia", 'city_id' =>44, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Ancud", 'abbreviation' => "Ancud", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Castro", 'abbreviation' => "Castro", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chonchi", 'abbreviation' => "Chonchi", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Curaco de Vélez", 'abbreviation' => "Curaco de Vélez", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Dalcahue", 'abbreviation' => "Dalcahue", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Puqueldón", 'abbreviation' => "Puqueldón", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Queilén", 'abbreviation' => "Queilén", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quellón", 'abbreviation' => "Quellón", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quemchi", 'abbreviation' => "Quemchi", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quinchao", 'abbreviation' => "Quinchao", 'city_id' =>45, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Calbuco", 'abbreviation' => "Calbuco", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cochamó", 'abbreviation' => "Cochamó", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Fresia", 'abbreviation' => "Fresia", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Frutillar", 'abbreviation' => "Frutillar", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Llanquihue", 'abbreviation' => "Llanquihue", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Los Muermos", 'abbreviation' => "Los Muermos", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Maullín", 'abbreviation' => "Maullín", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Puerto Montt", 'abbreviation' => "Puerto Montt", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Puerto Varas", 'abbreviation' => "Puerto Varas", 'city_id' =>46, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Osorno", 'abbreviation' => "Osorno", 'city_id' =>47, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Puerto Octay", 'abbreviation' => "Puerto Octay", 'city_id' =>47, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Purranque", 'abbreviation' => "Purranque", 'city_id' =>47, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Puyehue", 'abbreviation' => "Puyehue", 'city_id' =>47, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Río Negro", 'abbreviation' => "Río Negro", 'city_id' =>47, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Pablo", 'abbreviation' => "San Pablo", 'city_id' =>47, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Juan de la Costa", 'abbreviation' => "San Juan de la ", 'city_id' =>47, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chaitén", 'abbreviation' => "Chaitén", 'city_id' =>48, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Futaleufú", 'abbreviation' => "Futaleufú", 'city_id' =>48, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Hualaihué", 'abbreviation' => "Hualaihué", 'city_id' =>48, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Palena", 'abbreviation' => "Palena", 'city_id' =>48, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Aysén", 'abbreviation' => "Aysén", 'city_id' =>49, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cisnes", 'abbreviation' => "Cisnes", 'city_id' =>49, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Guaitecas", 'abbreviation' => "Guaitecas", 'city_id' =>49, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cochrane", 'abbreviation' => "Cochrane", 'city_id' =>50, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "O'Higgins", 'abbreviation' => "O'Higgins", 'city_id' =>50, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Tortel", 'abbreviation' => "Tortel", 'city_id' =>50, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Coyhaique", 'abbreviation' => "Coyhaique", 'city_id' =>51, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lago Verde", 'abbreviation' => "Lago Verde", 'city_id' =>51, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Chile Chico", 'abbreviation' => "Chile Chico", 'city_id' =>52, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Río Ibáñez", 'abbreviation' => "Río Ibáñez", 'city_id' =>52, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Antártica", 'abbreviation' => "Antártica", 'city_id' =>53, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cabo de Hornos", 'abbreviation' => "Cabo de Hornos", 'city_id' =>53, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Laguna Blanca", 'abbreviation' => "Laguna Blanca", 'city_id' =>54, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Punta Arenas", 'abbreviation' => "Punta Arenas", 'city_id' =>54, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Río Verde", 'abbreviation' => "Río Verde", 'city_id' =>54, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Gregorio", 'abbreviation' => "San Gregorio", 'city_id' =>54, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Porvenir", 'abbreviation' => "Porvenir", 'city_id' =>55, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Primavera", 'abbreviation' => "Primavera", 'city_id' =>55, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Timaukel", 'abbreviation' => "Timaukel", 'city_id' =>55, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Natales", 'abbreviation' => "Natales", 'city_id' =>56, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Torres del Paine", 'abbreviation' => "Torres del Pain", 'city_id' =>56, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Colina", 'abbreviation' => "Colina", 'city_id' =>22, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lampa", 'abbreviation' => "Lampa", 'city_id' =>22, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Tiltil", 'abbreviation' => "Tiltil", 'city_id' =>22, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pirque", 'abbreviation' => "Pirque", 'city_id' =>23, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Puente Alto", 'abbreviation' => "Puente Alto", 'city_id' =>23, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San José de Maipo", 'abbreviation' => "San José de Mai", 'city_id' =>23, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Buin", 'abbreviation' => "Buin", 'city_id' =>24, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Calera de Tango", 'abbreviation' => "Calera de Tango", 'city_id' =>24, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Paine", 'abbreviation' => "Paine", 'city_id' =>24, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Bernardo", 'abbreviation' => "San Bernardo", 'city_id' =>24, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Alhué", 'abbreviation' => "Alhué", 'city_id' =>25, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Curacaví", 'abbreviation' => "Curacaví", 'city_id' =>25, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "María Pinto", 'abbreviation' => "María Pinto", 'city_id' =>25, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Melipilla", 'abbreviation' => "Melipilla", 'city_id' =>25, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Pedro", 'abbreviation' => "San Pedro", 'city_id' =>25, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cerrillos", 'abbreviation' => "Cerrillos", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Cerro Navia", 'abbreviation' => "Cerro Navia", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Conchalí", 'abbreviation' => "Conchalí", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "El Bosque", 'abbreviation' => "El Bosque", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Estación Central", 'abbreviation' => "Estación Centra", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Huechuraba", 'abbreviation' => "Huechuraba", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Independencia", 'abbreviation' => "Independencia", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Cisterna", 'abbreviation' => "La Cisterna", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Granja", 'abbreviation' => "La Granja", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Florida", 'abbreviation' => "La Florida", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Pintana", 'abbreviation' => "La Pintana", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "La Reina", 'abbreviation' => "La Reina", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Las Condes", 'abbreviation' => "Las Condes", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lo Barnechea", 'abbreviation' => "Lo Barnechea", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lo Espejo", 'abbreviation' => "Lo Espejo", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Lo Prado", 'abbreviation' => "Lo Prado", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Macul", 'abbreviation' => "Macul", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Maipú", 'abbreviation' => "Maipú", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Ñuñoa", 'abbreviation' => "Ñuñoa", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pedro Aguirre Cerda", 'abbreviation' => "Pedro Aguirre C", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Peñalolén", 'abbreviation' => "Peñalolén", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Providencia", 'abbreviation' => "Providencia", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Pudahuel", 'abbreviation' => "Pudahuel", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quilicura", 'abbreviation' => "Quilicura", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Quinta Normal", 'abbreviation' => "Quinta Normal", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Recoleta", 'abbreviation' => "Recoleta", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Renca", 'abbreviation' => "Renca", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Miguel", 'abbreviation' => "San Miguel", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Joaquín", 'abbreviation' => "San Joaquín", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "San Ramón", 'abbreviation' => "San Ramón", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Santiago", 'abbreviation' => "Santiago", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Vitacura", 'abbreviation' => "Vitacura", 'city_id' =>26, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "El Monte", 'abbreviation' => "El Monte", 'city_id' =>27, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Isla de Maipo", 'abbreviation' => "Isla de Maipo", 'city_id' =>27, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Padre Hurtado", 'abbreviation' => "Padre Hurtado", 'city_id' =>27, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Peñaflor", 'abbreviation' => "Peñaflor", 'city_id' =>27, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "Talagante", 'abbreviation' => "Talagante", 'city_id' =>27, 'created_at' => now(), 'updated_at' => now()]);
            DB::table('communes')->insert(['name' => "346 comunas", 'abbreviation' => "346 comunas", 'city_id' =>27, 'created_at' => now(), 'updated_at' => now()]);
        }
    }
}
